


const EventDetails = () => {
    const {name,id,img, price,description } = event;
    return (
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias excepturi animi ipsum doloribus similique eum voluptatibus quidem quis ullam reprehenderit, omnis ipsam accusamus sed consectetur illo minus aliquid accusantium soluta dolorem possimus impedit quae. Hic excepturi, voluptatem nam quod sed magnam voluptas dolorem laborum. At quod voluptate pariatur dolore repudiandae quos quibusdam quidem magni quisquam nam excepturi incidunt deserunt fugit nostrum magnam optio saepe tempore accusamus doloribus, beatae vel. Incidunt architecto voluptates eum voluptatem harum nam voluptas, praesentium officiis ratione quo alias culpa dolore possimus quas quis ipsum error impedit adipisci? In magnam saepe reprehenderit facere dignissimos officia fugit corrupti ipsa, rem ratione non excepturi itaque mollitia? Quas ab soluta molestiae sed assumenda iure nihil magnam eos alias illo consequatur unde et eligendi ducimus quidem quos similique excepturi ipsa dignissimos, blanditiis quam! Laboriosam magni autem molestias quod eaque nostrum aliquam veniam culpa sint totam, quia blanditiis ad iure magnam possimus officia architecto distinctio assumenda veritatis placeat facilis ipsa alias impedit fugit? Ipsam ullam tempora velit perspiciatis obcaecati dolorum consectetur eveniet itaque, debitis minima repellat a blanditiis placeat! Expedita corporis, perferendis temporibus et at similique consequatur, non minima sapiente assumenda nam odio libero porro culpa ipsam. Commodi voluptatibus sunt molestias quod reiciendis distinctio autem iste officiis placeat itaque cum facere voluptatum assumenda quas ex soluta a omnis earum qui, culpa dolores suscipit? Nisi, consequatur quibusdam? Vitae ex exercitationem ratione quos error similique eligendi perferendis dolorem, doloremque sint nulla voluptate nisi, atque quisquam quod pariatur minus at neque vel, ab provident nemo dolor! Consequatur odio cumque voluptatibus quidem? Eaque at dignissimos ullam modi porro, laudantium necessitatibus, tempore omnis quae sit nobis nulla esse corporis numquam repudiandae fuga harum natus facilis ad? Veniam culpa atque explicabo quibusdam quis earum voluptatum a error aut velit maiores repudiandae, incidunt aspernatur, beatae nostrum ipsam alias saepe.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias excepturi animi ipsum doloribus similique eum voluptatibus quidem quis ullam reprehenderit, omnis ipsam accusamus sed consectetur illo minus aliquid accusantium soluta dolorem possimus impedit quae. Hic excepturi, voluptatem nam quod sed magnam voluptas dolorem laborum. At quod voluptate pariatur dolore repudiandae quos quibusdam quidem magni quisquam nam excepturi incidunt deserunt fugit nostrum magnam optio saepe tempore accusamus doloribus, beatae vel. Incidunt architecto voluptates eum voluptatem harum nam voluptas, praesentium officiis ratione quo alias culpa dolore possimus quas quis ipsum error impedit adipisci? In magnam saepe reprehenderit facere dignissimos officia fugit corrupti ipsa, rem ratione non excepturi itaque mollitia? Quas ab soluta molestiae sed assumenda iure nihil magnam eos alias illo consequatur unde et eligendi ducimus quidem quos similique excepturi ipsa dignissimos, blanditiis quam! Laboriosam magni autem molestias quod eaque nostrum aliquam veniam culpa sint totam, quia blanditiis ad iure magnam possimus officia architecto distinctio assumenda veritatis placeat facilis ipsa alias impedit fugit? Ipsam ullam tempora velit perspiciatis obcaecati dolorum consectetur eveniet itaque, debitis minima repellat a blanditiis placeat! Expedita corporis, perferendis temporibus et at similique consequatur, non minima sapiente assumenda nam odio libero porro culpa ipsam. Commodi voluptatibus sunt molestias quod reiciendis distinctio autem iste officiis placeat itaque cum facere voluptatum assumenda quas ex soluta a omnis earum qui, culpa dolores suscipit? Nisi, consequatur quibusdam? Vitae ex exercitationem ratione quos error similique eligendi perferendis dolorem, doloremque sint nulla voluptate nisi, atque quisquam quod pariatur minus at neque vel, ab provident nemo dolor! Consequatur odio cumque voluptatibus quidem? Eaque at dignissimos ullam modi porro, laudantium necessitatibus, tempore omnis quae sit nobis nulla esse corporis numquam repudiandae fuga harum natus facilis ad? Veniam culpa atque explicabo quibusdam quis earum voluptatum a error aut velit maiores repudiandae, incidunt aspernatur, beatae nostrum ipsam alias saepe.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias excepturi animi ipsum doloribus similique eum voluptatibus quidem quis ullam reprehenderit, omnis ipsam accusamus sed consectetur illo minus aliquid accusantium soluta dolorem possimus impedit quae. Hic excepturi, voluptatem nam quod sed magnam voluptas dolorem laborum. At quod voluptate pariatur dolore repudiandae quos quibusdam quidem magni quisquam nam excepturi incidunt deserunt fugit nostrum magnam optio saepe tempore accusamus doloribus, beatae vel. Incidunt architecto voluptates eum voluptatem harum nam voluptas, praesentium officiis ratione quo alias culpa dolore possimus quas quis ipsum error impedit adipisci? In magnam saepe reprehenderit facere dignissimos officia fugit corrupti ipsa, rem ratione non excepturi itaque mollitia? Quas ab soluta molestiae sed assumenda iure nihil magnam eos alias illo consequatur unde et eligendi ducimus quidem quos similique excepturi ipsa dignissimos, blanditiis quam! Laboriosam magni autem molestias quod eaque nostrum aliquam veniam culpa sint totam, quia blanditiis ad iure magnam possimus officia architecto distinctio assumenda veritatis placeat facilis ipsa alias impedit fugit? Ipsam ullam tempora velit perspiciatis obcaecati dolorum consectetur eveniet itaque, debitis minima repellat a blanditiis placeat! Expedita corporis, perferendis temporibus et at similique consequatur, non minima sapiente assumenda nam odio libero porro culpa ipsam. Commodi voluptatibus sunt molestias quod reiciendis distinctio autem iste officiis placeat itaque cum facere voluptatum assumenda quas ex soluta a omnis earum qui, culpa dolores suscipit? Nisi, consequatur quibusdam? Vitae ex exercitationem ratione quos error similique eligendi perferendis dolorem, doloremque sint nulla voluptate nisi, atque quisquam quod pariatur minus at neque vel, ab provident nemo dolor! Consequatur odio cumque voluptatibus quidem? Eaque at dignissimos ullam modi porro, laudantium necessitatibus, tempore omnis quae sit nobis nulla esse corporis numquam repudiandae fuga harum natus facilis ad? Veniam culpa atque explicabo quibusdam quis earum voluptatum a error aut velit maiores repudiandae, incidunt aspernatur, beatae nostrum ipsam alias saepe.</div>

      
      
    );
};

export default EventDetails;